### ISSUE TITLE
In hexo 3.0, it's not work.

### ISSUE THREAD

**Issue by Svtter** [phoenixcw/hexo-renderer-mathjax#1]
Hexo 3.0 change `hexo.file` to `require('hexo-fs')` and need to install [hexo-fs](https://github.com/hexojs/hexo-fs) to make sure it works.

I write some code for this reason, but I deem it not the best way to solve this problem.
- index.js

```
//var file = hexo.file;
var file = require('hexo-fs');
```

**Comment by phoenixcw** [comment]
@Svtter 
Thanks for @ntalbs. He has fixed the bug and now you may have a try.
Thanks for your feedback!
